# Generated by Django 6.0.5 on 2026-07-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CHESS', 'Chess'), ('SUDOKU', 'Sudoku'), ('SCRAMBLE', 'Scramble'), ('CHECKERS', 'Checkers'), ('WHOT', 'Whot'), ('LUDO', 'Ludo')], max_length=20, unique=True)),
                ('tier', models.CharField(choices=[('FULL', 'Full Rate'), ('MID', 'Mid Tier'), ('LOWER', 'Lower Tier')], max_length=10)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
