# Generated by Django 6.0.5 on 2026-07-03 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_made_at', models.DateTimeField(auto_now_add=True)),
                ('session_date', models.DateField()),
                ('session_start_time', models.TimeField()),
                ('actual_duration_hours', models.DecimalField(decimal_places=2, default=3, max_digits=4)),
                ('is_streak', models.BooleanField(default=False)),
                ('streak_group_id', models.UUIDField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('surcharge_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.gametype')),
            ],
            options={
                'ordering': ['session_date', 'session_start_time'],
            },
        ),
    ]
