# Generated by Django 6.0.6 on 2026-07-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(default='Owerri (address not recorded)', max_length=255),
            preserve_default=False,
        ),
    ]
